// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task_16.Context;

#nullable disable

namespace Task_16.Migrations
{
    [DbContext(typeof(Task16DbContext))]
    [Migration("20231219182039_mg_5")]
    partial class mg_5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Task_16.Areas.admin.Models.Entities.Statistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Statistic")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StatisticsDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatisticsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("StatisticsPercent")
                        .HasColumnType("real");

                    b.Property<float>("StatisticsPercentage")
                        .HasColumnType("real");

                    b.Property<float>("StatisticsPercentages")
                        .HasColumnType("real");

                    b.Property<DateTime>("StatisticsTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatisticsVisit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatisticsVisits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statistics");
                });
#pragma warning restore 612, 618
        }
    }
}
